language: node_js
node_js:
  - "6"
before_script:
  - npm install
  - cp ./config/travis/app4_tst2_s1_wb_key.pem ~
  - cp ./config/travis/app4_tst2_s1_wb_pub.pem ~
  - swagger project start
script:
  - swagger project test
  # - swagger project start &
  # - swagger project test